---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-configmap
data:
  MYSQL_PASSWORD: 'supersecretpassword'
  NEXTCLOUD_ADMIN_USER: filbot
  NEXTCLOUD_ADMIN_PASSWORD: 'supersecretpassword'
  VIRTUALHOST: nc.filbot.net
  LETSENCRYPT_HOST: nc.filbot.net
  LETSENCRYPT_EMAIL: predatorian3@gmail.com
...
